<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'TwitterOAuth\\' => array($vendorDir . '/ricardoper/twitteroauth'),
    'Madcoda' => array($vendorDir . '/madcoda/php-youtube-api/lib'),
);
